name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v5

      - name: set up node.jobs
        uses: actions/setup-node@v5

      - name: install dependencies
        run: npm install

      - name: run test
        run: npm test